version: "3.8"
services: 
    service1:
        build: ./service1
        image: hjtindale/doodle_frontend:latest
        container_name: doodle_frontend
        ports:
        - target: 5000
          published: 80
        environment:
          DATABASE_URI: ${DATABASE_URI}
        deploy:
          replicas: 4
    service2:
        build: ./service2
        image: hjtindale/doodle_backend_1:latest
        container_name: doodle_aesthetics
        deploy:
          replicas: 4
    service3:
        build: ./service3
        image: hjtindale/doodle_backend_2:latest
        container_name: doodle_subjects
        deploy:
          replicas: 4
    service4:
        build: ./service4
        image: hjtindale/doodle_backend_3:latest
        container_name: doodle_doodle
        deploy:
          replicas: 4
