all:
  children:
    managers:
      hosts:
        manager:
    workers:
      hosts:
        worker-a:
    nginxloadbalancer:
      hosts:
        nginx:
  vars:
    ansible_user: jenkins
    ansible_ssh_private_key_file: '~/.ssh/ansible_id_rsa'
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

